/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSignalsIndexRouteImport } from './routes/_authenticated/signals/index'
import { Route as AuthenticatedSignalsSignalIdRouteImport } from './routes/_authenticated/signals/$signalId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSignalsIndexRoute =
  AuthenticatedSignalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSignalsRoute,
  } as any)
const AuthenticatedSignalsSignalIdRoute =
  AuthenticatedSignalsSignalIdRouteImport.update({
    id: '/$signalId',
    path: '/$signalId',
    getParentRoute: () => AuthenticatedSignalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signals': typeof AuthenticatedSignalsRouteWithChildren
  '/signals/$signalId': typeof AuthenticatedSignalsSignalIdRoute
  '/signals/': typeof AuthenticatedSignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signals/$signalId': typeof AuthenticatedSignalsSignalIdRoute
  '/signals': typeof AuthenticatedSignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRouteWithChildren
  '/_authenticated/signals/$signalId': typeof AuthenticatedSignalsSignalIdRoute
  '/_authenticated/signals/': typeof AuthenticatedSignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/signals'
    | '/signals/$signalId'
    | '/signals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/signals/$signalId'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/signals'
    | '/_authenticated/signals/$signalId'
    | '/_authenticated/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/': {
      id: '/_authenticated/signals/'
      path: '/'
      fullPath: '/signals/'
      preLoaderRoute: typeof AuthenticatedSignalsIndexRouteImport
      parentRoute: typeof AuthenticatedSignalsRoute
    }
    '/_authenticated/signals/$signalId': {
      id: '/_authenticated/signals/$signalId'
      path: '/$signalId'
      fullPath: '/signals/$signalId'
      preLoaderRoute: typeof AuthenticatedSignalsSignalIdRouteImport
      parentRoute: typeof AuthenticatedSignalsRoute
    }
  }
}

interface AuthenticatedSignalsRouteChildren {
  AuthenticatedSignalsSignalIdRoute: typeof AuthenticatedSignalsSignalIdRoute
  AuthenticatedSignalsIndexRoute: typeof AuthenticatedSignalsIndexRoute
}

const AuthenticatedSignalsRouteChildren: AuthenticatedSignalsRouteChildren = {
  AuthenticatedSignalsSignalIdRoute: AuthenticatedSignalsSignalIdRoute,
  AuthenticatedSignalsIndexRoute: AuthenticatedSignalsIndexRoute,
}

const AuthenticatedSignalsRouteWithChildren =
  AuthenticatedSignalsRoute._addFileChildren(AuthenticatedSignalsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
