/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSignalsIndexRouteImport } from './routes/_authenticated/signals/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug'
import { Route as AuthenticatedSignalsSignalIdRouteImport } from './routes/_authenticated/signals/$signalId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugUsersRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/users'
import { Route as AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/boards/$boardId/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/boards/$boardId/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSignalsIndexRoute =
  AuthenticatedSignalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSignalsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugRoute =
  AuthenticatedWorkspacesWorkspaceSlugRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsSignalIdRoute =
  AuthenticatedSignalsSignalIdRouteImport.update({
    id: '/$signalId',
    path: '/$signalId',
    getParentRoute: () => AuthenticatedSignalsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugUsersRoute =
  AuthenticatedWorkspacesWorkspaceSlugUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRouteImport.update(
    {
      id: '/tasks/$taskId',
      path: '/tasks/$taskId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signals': typeof AuthenticatedSignalsRouteWithChildren
  '/signals/$signalId': typeof AuthenticatedSignalsSignalIdRoute
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteWithChildren
  '/signals/': typeof AuthenticatedSignalsIndexRoute
  '/workspaces/$workspaceSlug/users': typeof AuthenticatedWorkspacesWorkspaceSlugUsersRoute
  '/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/boards/$boardId': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteWithChildren
  '/workspaces/$workspaceSlug/boards/$boardId/': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute
  '/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signals/$signalId': typeof AuthenticatedSignalsSignalIdRoute
  '/signals': typeof AuthenticatedSignalsIndexRoute
  '/workspaces/$workspaceSlug/users': typeof AuthenticatedWorkspacesWorkspaceSlugUsersRoute
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/boards/$boardId': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute
  '/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRouteWithChildren
  '/_authenticated/signals/$signalId': typeof AuthenticatedSignalsSignalIdRoute
  '/_authenticated/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteWithChildren
  '/_authenticated/signals/': typeof AuthenticatedSignalsIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/users': typeof AuthenticatedWorkspacesWorkspaceSlugUsersRoute
  '/_authenticated/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/boards/$boardId': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId': typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/signals'
    | '/signals/$signalId'
    | '/workspaces/$workspaceSlug'
    | '/signals/'
    | '/workspaces/$workspaceSlug/users'
    | '/workspaces/$workspaceSlug/'
    | '/workspaces/$workspaceSlug/boards/$boardId'
    | '/workspaces/$workspaceSlug/boards/$boardId/'
    | '/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/signals/$signalId'
    | '/signals'
    | '/workspaces/$workspaceSlug/users'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/$workspaceSlug/boards/$boardId'
    | '/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/signals'
    | '/_authenticated/signals/$signalId'
    | '/_authenticated/workspaces/$workspaceSlug'
    | '/_authenticated/signals/'
    | '/_authenticated/workspaces/$workspaceSlug/users'
    | '/_authenticated/workspaces/$workspaceSlug/'
    | '/_authenticated/workspaces/$workspaceSlug/boards/$boardId'
    | '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/'
    | '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/': {
      id: '/_authenticated/signals/'
      path: '/'
      fullPath: '/signals/'
      preLoaderRoute: typeof AuthenticatedSignalsIndexRouteImport
      parentRoute: typeof AuthenticatedSignalsRoute
    }
    '/_authenticated/workspaces/$workspaceSlug': {
      id: '/_authenticated/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/$signalId': {
      id: '/_authenticated/signals/$signalId'
      path: '/$signalId'
      fullPath: '/signals/$signalId'
      preLoaderRoute: typeof AuthenticatedSignalsSignalIdRouteImport
      parentRoute: typeof AuthenticatedSignalsRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/': {
      id: '/_authenticated/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/users': {
      id: '/_authenticated/workspaces/$workspaceSlug/users'
      path: '/users'
      fullPath: '/workspaces/$workspaceSlug/users'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugUsersRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/boards/$boardId': {
      id: '/_authenticated/workspaces/$workspaceSlug/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/workspaces/$workspaceSlug/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/': {
      id: '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/boards/$boardId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId': {
      id: '/_authenticated/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/workspaces/$workspaceSlug/boards/$boardId/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute
    }
  }
}

interface AuthenticatedSignalsRouteChildren {
  AuthenticatedSignalsSignalIdRoute: typeof AuthenticatedSignalsSignalIdRoute
  AuthenticatedSignalsIndexRoute: typeof AuthenticatedSignalsIndexRoute
}

const AuthenticatedSignalsRouteChildren: AuthenticatedSignalsRouteChildren = {
  AuthenticatedSignalsSignalIdRoute: AuthenticatedSignalsSignalIdRoute,
  AuthenticatedSignalsIndexRoute: AuthenticatedSignalsIndexRoute,
}

const AuthenticatedSignalsRouteWithChildren =
  AuthenticatedSignalsRoute._addFileChildren(AuthenticatedSignalsRouteChildren)

interface AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute
}

const AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdTasksTaskIdRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugUsersRoute: typeof AuthenticatedWorkspacesWorkspaceSlugUsersRoute
  AuthenticatedWorkspacesWorkspaceSlugIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceSlugRouteChildren: AuthenticatedWorkspacesWorkspaceSlugRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugUsersRoute:
      AuthenticatedWorkspacesWorkspaceSlugUsersRoute,
    AuthenticatedWorkspacesWorkspaceSlugIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugBoardsBoardIdRouteRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceSlugRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRouteWithChildren,
  AuthenticatedWorkspacesWorkspaceSlugRoute:
    AuthenticatedWorkspacesWorkspaceSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
